### ISSUE TITLE
Fix code scanning alert - disallow control characters in regular expressions

### ISSUE THREAD

**Issue by webmsgr** [insberr/schedule-script#2]
Tracking issue for:
- [ ] https://github.com/insberr/schedule-script/security/code-scanning/26

pls remove all of that weird backspace code you are scaring my family

**Comment by insberr** [comment]
What am I supposed to use instead then?

**Comment by webmsgr** [comment]
The code isn't used afaik

**Comment by insberr** [comment]
should be fixed now. fixed in commit 256ace8781339d4ab0e2065a2a3a0e690eb8bfeb
